language: node_js
node_js:
  - 0.10.28

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - npm install -g karma

script:
  - karma start  --browsers=Firefox
